# Generated by Django 6.0.6 on 2026-07-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_remove_item_image_url_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='media_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
