# Generated by Django 4.2.5 on 2024-01-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
