# Generated by Django 5.0.1 on 2024-02-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0009_profile_facebook_link_profile_homepage_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='post',
            name='post_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
