# Generated by Django 6.0.6 on 2026-06-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0010_remove_post_post_image_remove_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image_url',
        ),
        migrations.AddField(
            model_name='post',
            name='post_media',
            field=models.FileField(blank=True, null=True, upload_to='post_media/'),
        ),
    ]
