# Generated by Django 6.0.6 on 2026-06-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0011_remove_post_post_image_url_post_post_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
