# Generated by Django 6.0.6 on 2026-07-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0013_post_latitude_post_location_name_post_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='length_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
