# Generated by Django 6.0.6 on 2026-07-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0015_backfill_length_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('green', 'Easy'), ('blue', 'Moderate'), ('red', 'Difficult'), ('black', 'Severe')], max_length=10, null=True),
        ),
    ]
