# Generated by Django 6.0.6 on 2026-07-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0016_add_difficulty_to_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='elevations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='total_ascent_m',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
