# Generated by Django 6.0.6 on 2026-07-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0017_add_elevations_total_ascent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='media_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
