# Generated by Django 6.0.6 on 2026-07-04 23:24

import cycling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0018_post_media_url_profile_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=cycling.models._attachment_upload_path),
        ),
    ]
