# Generated by Django 6.0.6 on 2026-07-04 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0019_post_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
