# Generated by Django 6.0.6 on 2026-07-05 08:10

import cycling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0020_delete_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=cycling.models._comment_attachment_upload_path),
        ),
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='comment_media/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='media_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
