# Generated by Django 6.0.6 on 2026-07-05 08:40

import cycling.models
import media_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0021_comment_attachment_comment_media_comment_media_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=media_storage.attachment_storage, upload_to=cycling.models._comment_attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='comment',
            name='media',
            field=models.FileField(blank=True, null=True, storage=media_storage.post_media_storage, upload_to='comment_media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=media_storage.attachment_storage, upload_to=cycling.models._attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_media',
            field=models.FileField(blank=True, null=True, storage=media_storage.post_media_storage, upload_to='post_media/'),
        ),
    ]
