"""
Django settings for social project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import dj_database_url
from pathlib import Path
import os
import ssl
from dotenv import load_dotenv
ssl._create_default_https_context = ssl._create_unverified_context

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# IMPORTANT: pass the path explicitly. python-dotenv's auto-search walks up
# from *this file's own directory* (social/) when run as a real script (every
# real invocation — runserver, collectstatic, test, gunicorn — not just `-c`),
# so an unrelated social/.env would get picked up instead of the real one at
# the project root, silently. That's not hypothetical: this project used to
# have exactly such a file, which meant DEBUG/SECRET_KEY/ALLOWED_HOSTS/
# DATABASE_URL/CLOUDINARY_URL were silently falling back to hardcoded
# defaults on every normal run. Being explicit here avoids the whole class of
# bug regardless of what other .env-like files might exist anywhere else.
load_dotenv(BASE_DIR / '.env', override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# This default is ONLY for local dev — Railway (or any real deploy) must set
# a real SECRET_KEY env var. It's clearly fake so it can never be mistaken
# for something to keep secret.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-local-dev-only-do-not-use-in-prod')

# SECURITY WARNING: don't run with debug turned on in production!
# Local default is True; Railway sets DEBUG=False explicitly.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

# Railway injects this automatically with the service's public domain.
RAILWAY_PUBLIC_DOMAIN = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

# RAILWAY_ENVIRONMENT is set whenever the app is actually running on Railway.
# Their healthcheck/internal networking can present a Host header under a
# *.railway.app / *.up.railway.app subdomain that isn't knowable ahead of
# time, so allow the whole domain rather than 400ing the healthcheck.
if os.environ.get('RAILWAY_ENVIRONMENT'):
    ALLOWED_HOSTS += ['.railway.app', '.up.railway.app']

CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]
if RAILWAY_PUBLIC_DOMAIN and f'https://{RAILWAY_PUBLIC_DOMAIN}' not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RAILWAY_PUBLIC_DOMAIN}')

# Production security settings (manage.py check --deploy's checklist).
# Railway terminates TLS at its edge proxy and forwards plain HTTP internally
# with an X-Forwarded-Proto header, hence SECURE_PROXY_SSL_HEADER below.
X_FRAME_OPTIONS = 'DENY'

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Modest to start — raise once HTTPS is confirmed solid in production,
    # then consider SECURE_HSTS_PRELOAD.
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    'cycling',
    'core',
    'dashboard',
    'item',
    'conversation',

]

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'social.urls'

# NOTE: Django 5.1+ ignores the legacy STATICFILES_STORAGE/DEFAULT_FILE_STORAGE
# settings entirely in favor of STORAGES below — but we still assign
# STATICFILES_STORAGE as a plain string too, because django-cloudinary-storage's
# own `collectstatic` override (it replaces Django's built-in command — see
# cloudinary_storage/management/commands/collectstatic.py) reads
# settings.STATICFILES_STORAGE directly and raises AttributeError if it's
# unset. That override is designed for hosting static files ON Cloudinary
# (StaticCloudinaryStorage); since we keep static files on WhiteNoise instead,
# its copy_file() silently no-ops for every file *unless* you pass
# --upload-unhashed-files. Always run collectstatic with that flag — see
# DEPLOY.md.
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATIC_ROOT = BASE_DIR / "staticfiles"


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'social.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Railway injects DATABASE_URL for the attached Postgres plugin. Locally (and
# in CI), when it isn't set, fall back to the same SQLite file as always.
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Media storage: Railway's filesystem is ephemeral, so uploaded media must
# live on Cloudinary in production. Locally/in CI, when CLOUDINARY_URL isn't
# set, media keeps using local MEDIA_ROOT exactly as before — this must
# never accidentally require network access to run the app or the tests.
# Static files are never affected: they stay on WhiteNoise.
CLOUDINARY_URL = os.environ.get('CLOUDINARY_URL', '')

# Django 5.1+ only reads the STORAGES dict — the legacy DEFAULT_FILE_STORAGE/
# STATICFILES_STORAGE settings are no longer consulted for actual storage
# resolution (STATICFILES_STORAGE above is kept only to satisfy
# django-cloudinary-storage's collectstatic override, see the note there).
STORAGES = {
    "default": {
        "BACKEND": (
            "cloudinary_storage.storage.MediaCloudinaryStorage"
            if CLOUDINARY_URL
            else "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_BACKEND = 'backend.email_backend.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_USER') # Login email address, Stored as an environment varaible
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASSWORD') #App Password set from gmail, Stored as an environment varaible

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {"handlers": ["console"], "level": "WARNING"},
    "loggers": {
        "django.request": {"handlers": ["console"], "level": "ERROR", "propagate": False},
    },
}